// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class Buy {
  static encode(message: Buy, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.amount);

    writer.uint32(16);
    writer.uint64(message.maxSolCost);
  }

  static decode(reader: Reader, length: i32): Buy {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Buy();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.amount = reader.uint64();
          break;

        case 2:
          message.maxSolCost = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  amount: u64;
  maxSolCost: u64;

  constructor(amount: u64 = 0, maxSolCost: u64 = 0) {
    this.amount = amount;
    this.maxSolCost = maxSolCost;
  }
}
