// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class CompleteEvent {
  static encode(message: CompleteEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.user);

    writer.uint32(18);
    writer.string(message.mint);

    writer.uint32(26);
    writer.string(message.bondingCurve);

    writer.uint32(32);
    writer.int64(message.timestamp);
  }

  static decode(reader: Reader, length: i32): CompleteEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompleteEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.user = reader.string();
          break;

        case 2:
          message.mint = reader.string();
          break;

        case 3:
          message.bondingCurve = reader.string();
          break;

        case 4:
          message.timestamp = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  user: string;
  mint: string;
  bondingCurve: string;
  timestamp: i64;

  constructor(
    user: string = "",
    mint: string = "",
    bondingCurve: string = "",
    timestamp: i64 = 0
  ) {
    this.user = user;
    this.mint = mint;
    this.bondingCurve = bondingCurve;
    this.timestamp = timestamp;
  }
}
